### ISSUE TITLE
Tech Talk 1 Individual - Nolan

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#22]
**Nolan Platt | Data Structures Challenge 1 Ticket**
[Source Code](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge1/Challenge1.java)
[Replit Runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge1/Challenge1.java) 

Task | Tangible | Scoring 
------ | ------- | --------
Code (queue add/delete, merge, build stack to reverse) + snippets + Replit runtime | [Challenge1.java file](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge1/Challenge1.java), [starter challenge commit](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/9c9eb6ca6fb5fc1c81feaabca5b826dd72bc643b), [fix syntax](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/72eee9eeec180a454df9001fc54a79e3cab4975b), [add menu system for all challenges](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/4bfc89fce0a6d2454bed7fdf61c443415c31ff11) | 3/3
Github review page w/ code snippets | [on my Jekyll](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures) | 1/1

Total Score = (Indi Score) + Group Score
Group Score = .85/1
Total Score = 4 + .85
_**Final Scoring**_:  **_4.85/5_**

I completed all my tasks in a very reasonable amount of time. I had no errors completing any of the challenges. I documented all of my tasks with tangibles and commits, as seen above. I also made sure to make a clean UI and user input on my Repl.it so that the user can easily navigate all of my challenges without confusion.

**Comment by samkoenig9** [comment]
+1: Github review page, both described in notes
+1: comments in code
+1: add
<img width="393" alt="Screen Shot 2022-03-21 at 8 32 11 AM" src="https://user-images.githubusercontent.com/72891935/159295517-82c317ba-ea6f-465f-9d8c-e815694808b9.png">
+2: delete
<img width="253" alt="image" src="https://user-images.githubusercontent.com/72891935/159295687-61fcc5dd-7089-4a5d-9a8c-24f2d64746cb.png">
+1: comments in code
+1: merge 2 queues
<img width="490" alt="image" src="https://user-images.githubusercontent.com/72891935/159295980-1bbc99f1-0c30-440a-abda-b77eb41b9718.png">
+2: class definition
+1: comments and purpose tester
+1: reverse order test case

Total checks: 12/12
Team score: .85/1

Total Score: 4.85/5

Reviewed for Nolan by Sam Koenig
