### ISSUE TITLE
Tech Talk 1 Individual - Rishi

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#24]
Overall score: (6/12) + (0.85/1) = **2.85/5**; Graded by Caleb Kim
View Jekyll [here](https://rpeddakama.github.io/CSA-Data-Structures/)

**Comment by calebkimsd** [comment]
Grading Score: /4

(checks/12 = points/4) + Team score.

- [ ]  One check, both are described in notes: Show understanding and description in Github Pages
- [ ] One check for comments: Comments are present
- [ ] One check for Add, running example:  Able  to add
- [ ] Two checks for Delete, one for individual implementation of Delete and one for running example: Able to dequeue and add to the queue
- [ ] 
- [ ] One check for comments: 
- [ ] Two checks, one for individual implementation of Merge method(s) and one for running example: Merging two different queues together in numerical order.
- [ ] 
- [ ] Two checks, class definition:
- [ ] 
- [ ] One check, comments, and general-purpose tester: Tester is present with example 
- [ ] One check, reverse order test case from Queue to Stack:
