### ISSUE TITLE
Tech Talk 2 Individual - Ashwin

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#27]
Total grading: lost 50% on each task --> 6 indiv checks = 2/4 + 0.85/1 = 2.85/5
- [Replit link](https://replit.com/@ashwinbabu888/AP-CSA-Data-Structures)
- Code snippets and learning takeaways are on gh-pages branch README.md

Task | Tangibles | Grading | Comments
---- | --------- | ------- | ---------
GitHub pages |  [website link](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/) | 1/1 | website has submenus and correctly displays important information
Queue/add/delete |  [queue add code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge1/challenge1.java#L39-L50), [queue delete code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge1/challenge1.java#L53-L62) | 2/4 | 1 point for having comments, having a running add function, implementing delete queue method, and running delete function
Merge 2 queues | [merge queues code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge1/challenge1.java#L77-L127) | 1/3 | 1 point for comments, implementing merge method, and having it functionally running
Build stack + reverse queue order | [reverse queue code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge1/challenge1.java#L129-L153), [build stack code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge1/challenge1.java#L63-L75) | 2/4 | 1 point for defining classes for each function, comments, and functional reverse order method.

**Comment by KrispyKremeSavage** [comment]
1.85/5, Eshaan Parlikar
