### ISSUE TITLE
Tech Talk 2 Individual - Nolan

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#28]
**Total Score: 2.5 + _3_**  = 5.5/5 (graded by Sam Koenig)
**Nolan Platt | Data Structures Challenge 2 Ticket**
[Source Code 1](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge2/Challenge2.java)
[Source Code 2](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge2/imports/Calculator.java)

[GitHub Review  Page](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures)

[Replit Runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge2/Challenge2.java) 

Task | Tangible | Scoring 
------ | ------- | --------
Indi Data Challenge & GitHub Pages| [Challenge2.java file](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge2/Challenge2.java), [Calculator.java file](https://github.com/nolanplatt/AP-CSA-Data-Structures/blob/main/challenge2/imports/Calculator.java), [initial commit](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/d87d194aa40a5b45e5dbba9be990fd4ff0101192), [final commit](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/7a7af74aebf1856a8eca689219f849b69cc20255), [wiki takeaways commit](https://github.com/nolanplatt/AP-CSA-Data-Structures/commit/b6d7830e304800d2f8c40ef2d5868a09c23bdc4b), [wiki with takeaways](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures) | 2.5/2
Group / Scrum Team Score | [Review Ticket](https://github.com/rpeddakama/AP-CSA-T3/issues/32) | 3/3

Total Score = (Indi Score) + Group Score
Group Score = unknown
Indi Score = 2.5/2
- _+1 extra credit point for extra credit SQRT function_
Total Score = 2.5 + 3 = 5.5/5

I completed all my tasks in a very reasonable amount of time. I had no errors completing any of the challenges. I documented all of my tasks with tangibles and commits, as seen above. I also made sure to make a clean UI and user input on my Repl.it so that the user can easily navigate all of my challenges without confusion.

**Comment by samkoenig9** [comment]
**Total Score: 2.5 + _TBA group score_/5** (graded by Sam Koenig)
Group: -/3 (not yet graded)
Individual: 2.5/2 (1.5 code + .5 github page + .5 extra credit)

Work is 100% complete and thorough. Calculator in repl is easy to use and menus work well. Lots of review writing on github page showing proof of knowledge and understanding of the topic. Square root calculator extra credit was also completed and functions properly.
