### ISSUE TITLE
Crossover Team Check

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#32]

**Comment by Chris-Ru** [comment]
Scrum Team GitHub pages (3 points)

 - Project Owner / Sponsor presentation and results of review
 - - Individual participated in Team Review
 - - Individual has notes or actions from Team review
 - 1st Code in GitHub
 - - Team repository is Created
 - - Individual can illustrate pulling Team code to their machine
 - - Individual has commit that shows intelligent capability within Team project: GitHub pages or Java Code or has Deployed and can access server.
 - - Individual shows an active Ticket with tangibles
 - 1st Deployment, including hosting plan in GitHub pages
 - - Hosting plan needs to include short term for Development plan, this should be running and link should be on GitHub pages
 - - Long term for how site will be maintained for customer

**Comment by jm1021** [comment]
Sponsor is APES Jay Hendricks.   Ideas on climate change.  Shared Open Stream map in meeting and got some future recommendations.  Should typewrter.

Has a flowchart show purpose of website.   Has a sign up for content updates.  

A lot of web tools, not sure where we are using Java.

Shared repository, they have 51 commits as a start.

Question about active tickets?  Shared GitHub pages and Scrum board.
