### ISSUE TITLE
Ashwin - Data Structure Challenge 2 Individual

### ISSUE THREAD

**Issue by ashwinbabu888** [rpeddakama/AP-CSA-T3#33]
Total: 5.5/5 (team grading - 3/3, individual - 2.5/2)
Grader: Caleb Kim

- [Replit link](https://replit.com/@ashwinbabu888/AP-CSA-Data-Structures)

Task | Tangibles | Grading | Comments
---- | --------- | ------- | --------
Calculator code, ec functions, replit, runnable test data, input option | [Calculator.java](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge2/imports/Calculator.java), [SQRT function](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge2/imports/Calculator.java#L189-L190), [Replit](https://replit.com/@ashwinbabu888/AP-CSA-Data-Structures), [test data](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge2/challenge2.java#L18-L27), [input with Scanner](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge2/challenge2.java#L12-L24) | 2/1.5 | the calculator is running and functional with input and test data, which can be tested through the Repl. I also did the square root function, which is 0.5 points extra credit.
GH page with learning | [GitHub page](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/) | 0.5/0.5 | all of the information, grading breakdown, and takeaways are organized well on the page

**Comment by calebkimsd** [comment]
Caleb Kim Grading: 2 / 1.5 + TEAM SCORE TBH

GitHub review page that documents key learnings using code snippets
Calculator page that shows highlights of work .5/.5
Explanation: Ashwin has his major takeaways located on his GitHub Pages that are also highlighted with code snippets and also explanations.

Calculator Code with optional extra credit functions, Replit Runtime, with runnable (no input) Test Data, and input option. 2/1.5
Explanation: Running on Replit with the optional square root extra credit. Has personal input/output functions that work.
