### ISSUE TITLE
Tech Talk 3 Individual - Nolan

### ISSUE THREAD

**Issue by nolanplatt** [rpeddakama/AP-CSA-T3#34]
**Total Score: 5/5** graded by Caleb Kim
**Nolan Platt | Data Structures Challenge 3 Ticket**

[Problem Solutions 1](https://github.com/nolanplatt/AP-CSA-Data-Structures/tree/main/challenge3)
  
[Replit Runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge3/Challenge3.java)
[GitHub Review  Page](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures)
[GitHub Tech Talk Notes](https://nolanplatt.github.io/AP-CSA-Data-Structures/techtalknotes)

Task | Tangible | Scoring 
------ | ------- | --------
GitHub Page w/ Notes on Big O Complexity | [analysis page](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures), [replit runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge3/Challenge3.java) | 1.25/1.25
Analysis | [analysis page](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures), [replit runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge3/Challenge3.java) | 1.25/1.25
Custom Bubble S, Selection S, Insertion S, Merge S | [analysis page](https://nolanplatt.github.io/AP-CSA-Data-Structures/datastructures), [replit runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge3/Challenge3.java), [source code](https://github.com/nolanplatt/AP-CSA-Data-Structures/tree/main/challenge3) | 1.25/1.25
Indi GitHub Pages, Replit, IntelliJ | [replit runtime](https://replit.com/@nolanplatt/AP-CSA-Data-Structures#challenge3/Challenge3.java), [indi github page](https://github.com/nolanplatt/AP-CSA-Data-Structures/tree/gh-pages), [indi java commits](https://github.com/nolanplatt/AP-CSA-Data-Structures/commits/main), [indi pages commits](https://github.com/nolanplatt/AP-CSA-Data-Structures/commits/gh-pages) | 1.25/1.25

I created my own data structure, **Advanced Array List (AAL)** for Objective 2 of this challenge. To be reviewed my Mr. Mortensen for maximum points on all data structures assignments past and present (excluding Calculator).

I completed all my tasks in a very reasonable amount of time. I had no errors completing any of the challenges. I documented all of my tasks with tangibles and commits, as seen above. I also made sure to make a clean UI and user input on my Replit so that the user can easily navigate all of my challenges without confusion.

**Comment by calebkimsd** [comment]
Caleb Kim Grading 5/5

Nolan went above the requirements and completed option 2 of this assignment. He created his custom data structure and used it to work on the sorts and analysis.

He has all the four sorts planted in replit and github 1.25/1.25
A Github page is presently showing his understanding of Big O notation and his implementations. 1.25/1.25
In the code, analysis is given in nanoseconds --> throws out his high and low and states that his merge sort was the fastest out of the 4. 1.25/1.25
Nolan has numerous commits that exceed the required 10 each. His code is present in the repl and the git shows multiple files.  All the files are organized and present in git. 1.25/1.25
