### ISSUE TITLE
Rishi - Week 3 Individual Check (Sort Algorithms)

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#35]
# Grade: 5/5; Crossover Partner: Navodit

### Grading Criteria
CB wants you to work with Bubble Sort, Selection Sort, Insertion Sort and Merge Sort.
Sorts and Analysis -- Coding, Comments, and Documentation
Build custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 25%
Build a GitHub page that describes Sort implementations and the Big O complexity of these Sorts. 25%
Analysis 25%
Establish analytics including: time, comparisons and swaps.
Average the results for each each Sort, run each at least 12 times and 5000 elements.  You should throw out High and Low when doing analysis.
Make your final/judgement on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.
Individual GitHub pages, Replit, IntelliJ 25%
Organize files, directories and menus for all weeks.
Make your GitHub pages fold into a personal portfolio
Make sure all Code and Analytics runs on Replit and IntelliJ
Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on Java and 10 commits on Pages)

**Comment by Navodit1603** [comment]
### Total Score: 5/5

* Has Comments and Own written algorithms for each sort. (1.25/1.25)
* Has Page for notes that explain each sort and their Big O notation. (1.25/1.25)
* Code prints out analytics for each sort and finds the average time. (1.25/1.25)
* Repl and Git Hub are sorted into different directories 
* Has a table to display all his personal DS work 
* Has 39 commits on shared repo for his Github Pages and DS work (1.25/1.25)
