### ISSUE TITLE
Ashwin - Week 3 Individual Check (Sort Algorithms)

### ISSUE THREAD

**Issue by ashwinbabu888** [rpeddakama/AP-CSA-T3#36]
Total grade: 4.25/5

Task | Grade | Tangibles | Comments
---- | ----- | -------- | ----------
Implement sorts | 1/1.25 | [add selection sort](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/commit/d3ecf341a797c347f44df92042f70d3726c5fe3e) | Not all sorts are complete, but knowledge of sorting with Java is there
GH pages with notes | 1.25/1.25 | [GH pages with notes](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/) | Tech talk notes are detailed
Analysis | 0.75/1.25 |  [analysis code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge3/challenge3.java) | Analysis isn't complete, but most of it is there.
Replit + IntelliJ |  1.25/1.25 | [GitHub Pages](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/) | Everything is organized well on GH pages and Replit

**Comment by VarnitGupta24** [comment]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Total grade: 4.25/5</p>

Task | Grade | Tangibles | Comments
-- | -- | -- | --
Implement sorts | 1/1.25 | add selection sort | Not all sorts are complete, but knowledge of sorting with Java is there
GH pages with notes | 1.25/1.25 | GH pages with notes | Tech talk notes are detailed
Analysis | 0.75/1.25 | analysis code | Analysis isn't complete, but most of it is there.
Replit + IntelliJ | 1.25/1.25 | GitHub Pages | Everything is organized well on GH pages and Replit

Total grade: 3.5/5

Task	Grade	Tangibles	Comments
Implement sorts	1/1.25	[add selection sort](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/commit/d3ecf341a797c347f44df92042f70d3726c5fe3e)	Not all sorts are complete, but knowledge of sorting with Java is there
[GH pages with notes](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/)	1.25/1.25	GH pages with notes	Tech talk notes are detailed
Analysis	0/1.25	[analysis code](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/blob/main/challenge3/challenge3.java)	Analysis isn't complete, but most of it is there.
Replit + IntelliJ	1.25/1.25	[GitHub Pages](https://ashwinbabu888.github.io/AP-CSA-Data-Structures/)	Everything is organized well on GH pages and Replit
Make your final/judgement on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.
Individual GitHub pages, Replit, IntelliJ 25% ( /1.25 points)
Organize files, directories and menus for all weeks.
Make your GitHub pages fold into a personal portfolio
Make sure all Code and Analytics runs on Replit and IntelliJ
Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on Java and 10 commits on Pages)
