### ISSUE TITLE
Ashwin - Study Week 1 Review Ticket

### ISSUE THREAD

**Issue by ashwinbabu888** [rpeddakama/AP-CSA-T3#41]
Total grade: 4.5/5

Task | Grade | Tangible | Comments
---- | ------- | --------- | ------------
Study plan | 1/1 | [study plan](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/wiki/AP-Exam-Study-Plan) | everything is detailed and thorough
MCQ corrections | 1/1 | [2015 MCQ corrections](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/wiki/2015-MCQ-Corrections) | corrections are specific and show learning
FRQs in Repl | 0.5/1 | [Repl](https://replit.com/@ashwinbabu888/AP-CSA-Data-Structures#Main.java) | FRQs are complete, but Repl is not entirely working
Study guide | 1/1 | [study guide](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/wiki/AP-Study-Guide) | it shows understanding of most topics in the curriculum
Crossover grading | 1/1 | [Michael's ticket](https://github.com/Archkitten/m22p1-nitro-code/issues/15) | I graded it correctly and it is well organized

**Comment by TKperson** [comment]
Total grade: 3.75/4.5

| Task | Grade | Tangible | Comments |
| :---- | ------ | ---------- | -----------: |
| Study plan | 1.5/1.5 | [study plan](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/wiki/AP-Exam-Study-Plan) | everything is detailed and thorough |
| MCQ corrections | 1.5/1.5 | [2015 MCQ corrections](https://github.com/ashwinbabu888/AP-CSA-Data-Structures/wiki/2015-MCQ-Corrections) | corrections are specific and show learning | 
| FRQs in Repl | 0.75 | [Repl](https://replit.com/@ashwinbabu888/AP-CSA-Data-Structures#Main.java) | Repl is not working completely |
