### ISSUE TITLE
Nolan -  Study Week 1 Review Ticket

### ISSUE THREAD

**Issue by nolanplatt** [rpeddakama/AP-CSA-T3#42]
Grade: 4.5/5 - graded by  Arch
[Study plan for week](https://nolanplatt.github.io/AP-CSA-Data-Structures/tpt)
[MCQ results and corrections](https://nolanplatt.github.io/AP-CSA-Data-Structures/frqs)
[FRQS in Repl](https://replit.com/@nolanplatt/FRQs#2015/Q1.java)
[FRQs Screenshots](https://nolanplatt.github.io/AP-CSA-Data-Structures/frqs)

**Comment by Archkitten** [comment]
## Overall Score: 4.25/5
### Graded by: Arch Huang

- [x] [Study plan](https://nolanplatt.github.io/AP-CSA-Data-Structures/tpt)
- [x] [MCQ reflection and self grade](https://nolanplatt.github.io/AP-CSA-Data-Structures/frqs)
- [x] FRQs in REPL
  - [FRQ reflection and self grade](https://nolanplatt.github.io/AP-CSA-Data-Structures/frqs)
  - FRQ Replit runtime compiles, must use:
    - javac Q1.java
    - java Q1
    - etc for other questions
    - Q3 and Q4 don't compile -0.25
- [ ] Individual Self Study guide
  - Missing -0.5
