### ISSUE TITLE
Tech Talk 0 Individual - Rishi

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#6]
[Here](https://github.com/rpeddakama/CSA-Data-Structures) is my GitHub source code.
[Here](https://replit.com/@RishiPeddakama/CSA-Data-Structures#Main.java) is the running version in replit.

**Comment by ashwinbabu888** [comment]
5/5

The menu is fully working. Rishi displayed complete knowledge of data structures by using minimal code and importing classes from different files to run on the main class.

Overall, he has many commits with clear evidence of changes and work, and his end product has concise code and is completely functional.

**Comment by calebkimsd** [comment]
Caleb Kim Grading:

Score: 100: 3/3

Comments: 
- able to input two different integers and swap them with each other [line 14-15](https://replit.com/@RishiPeddakama/CSA-Data-Structures#src/Swap.java)
- Has the matrix code, swap code, and also the menu that operates and organizes them.
- Tons of comments next to code to navigate and guide readers
